// <auto-generated />
using System;
using HollowKnightAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HollowKnightAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231209212857_MigrationPersonagens")]
    partial class MigrationPersonagens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HollowKnightAPI.models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaItem")
                        .HasColumnType("int");

                    b.Property<string>("DescricaoItem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoItem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdItem")
                        .HasColumnType("int");

                    b.Property<string>("NomeItem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonagemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonagemId");

                    b.ToTable("TB_ITENS");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaItem = 1,
                            DescricaoItem = "Sussura sua localização ao portador sempre que o mapa estiver aberto",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/7/7d/Wayward_Compass.png/revision/latest/scale-to-width-down/76?cb=20231011215858&path-prefix=pt",
                            IdItem = 1,
                            NomeItem = "Bússula Caprichosa"
                        },
                        new
                        {
                            Id = 2,
                            CategoriaItem = 1,
                            DescricaoItem = "Um enxame seguirá o portador e coletará quaisquer Geo deixado no chão.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/8/8a/Gathering_Swarm.png/revision/latest/scale-to-width-down/76?cb=20231011220242&path-prefix=pt",
                            IdItem = 2,
                            NomeItem = "Enxame de Colecionadores"
                        },
                        new
                        {
                            Id = 3,
                            CategoriaItem = 1,
                            DescricaoItem = "Quando recuperando-se de dano recebido, o portador permanecerá invulnerável por mais tempo.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/f/f2/Stalwart_Shell.png/revision/latest/scale-to-width-down/76?cb=20230731195337&path-prefix=pt",
                            IdItem = 3,
                            NomeItem = "Carapaça Robusta"
                        },
                        new
                        {
                            Id = 4,
                            CategoriaItem = 1,
                            DescricaoItem = "Aumenta a quantidade de ALMA recebida quando um oponente é atingido com o ferrão.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/c/ca/Soul_Catcher.png/revision/latest/scale-to-width-down/76?cb=20231011220646&path-prefix=pt",
                            IdItem = 4,
                            NomeItem = "Apanhador de Almas"
                        },
                        new
                        {
                            Id = 5,
                            CategoriaItem = 1,
                            DescricaoItem = "Quando dano é recebido, brotam-se vinhas espinhentas que machucam inimigos próximos.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/6/6c/Soul_Eater.png/revision/latest/scale-to-width-down/76?cb=20230731195650&path-prefix=pt",
                            IdItem = 5,
                            NomeItem = "Pedra do Xamã"
                        },
                        new
                        {
                            Id = 6,
                            CategoriaItem = 1,
                            DescricaoItem = "Aumenta consideravelmente a quantidade de ALMA recebida quando um oponente é atingido com o ferrão.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/7/7d/Wayward_Compass.png/revision/latest/scale-to-width-down/76?cb=20231011215858&path-prefix=pt",
                            IdItem = 6,
                            NomeItem = "Devorador de Almas"
                        },
                        new
                        {
                            Id = 7,
                            CategoriaItem = 1,
                            DescricaoItem = "Permite que o portador esquive-se mais frequentemente assim como esquivar-se para baixo.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/8/8f/Thorns_of_Agony.png/revision/latest/scale-to-width-down/76?cb=20230802200324&path-prefix=pt",
                            IdItem = 7,
                            NomeItem = "Espinhos da Agonia"
                        },
                        new
                        {
                            Id = 8,
                            CategoriaItem = 1,
                            DescricaoItem = "Quando próximo a morte, a força do portador irá aumentar.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/4/4f/Fury_of_the_Fallen.png/revision/latest/scale-to-width-down/76?cb=20230802203206&path-prefix=pt",
                            IdItem = 8,
                            NomeItem = "Fúria dos Caídos"
                        },
                        new
                        {
                            Id = 9,
                            CategoriaItem = 1,
                            DescricaoItem = "Reduz o custo de ALMA para a canalização de magias",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/3/33/Spell_Twister.png/revision/latest/scale-to-width-down/76?cb=20231011212430&path-prefix=pt",
                            IdItem = 9,
                            NomeItem = "Dobrador de Magias"
                        },
                        new
                        {
                            Id = 10,
                            CategoriaItem = 1,
                            DescricaoItem = "Mantém seu portador firme, prevenindo-o de recuar quando atingir um inimigo com o Ferrão.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/f/f5/Steady_Body.png/revision/latest/scale-to-width-down/76?cb=20231011221422&path-prefix=pt",
                            IdItem = 10,
                            NomeItem = "Corpo Firme"
                        },
                        new
                        {
                            Id = 11,
                            CategoriaItem = 1,
                            DescricaoItem = "Aumenta a força do ferrão do portador, causando inimigos a recuar mais quando atingidos.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/f/f6/Heavy_Blow.png/revision/latest/scale-to-width-down/76?cb=20231011222923&path-prefix=pt",
                            IdItem = 11,
                            NomeItem = "Golpe Pesado"
                        },
                        new
                        {
                            Id = 12,
                            CategoriaItem = 1,
                            DescricaoItem = "Permite o portador cortar muito mais rapidamente com seu ferrão.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/5/5f/Quick_Slash.png/revision/latest/scale-to-width-down/76?cb=20231011223343&path-prefix=pt",
                            IdItem = 12,
                            NomeItem = "Corte Rápido"
                        },
                        new
                        {
                            Id = 13,
                            CategoriaItem = 1,
                            DescricaoItem = "Aumenta o alcance do ferrão do portador.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/d/d1/Longnail.png/revision/latest/scale-to-width-down/76?cb=20231011223530&path-prefix=pt",
                            IdItem = 13,
                            NomeItem = "Ferrão Longo"
                        },
                        new
                        {
                            Id = 14,
                            CategoriaItem = 1,
                            DescricaoItem = "Aumenta consideravelmente o alcance do ferrão do portador.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/6/69/Mark_of_Pride.png/revision/latest/scale-to-width-down/76?cb=20231011223649&path-prefix=pt",
                            IdItem = 14,
                            NomeItem = "Marca de Orgulho"
                        },
                        new
                        {
                            Id = 15,
                            CategoriaItem = 1,
                            DescricaoItem = "Protege o portador com uma carapaça dura enquanto estiver focando ALMA.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/2/21/Baldur_Shell.png/revision/latest/scale-to-width-down/76?cb=20231011223844&path-prefix=pt",
                            IdItem = 15,
                            NomeItem = "Carapaça de Baldur"
                        },
                        new
                        {
                            Id = 16,
                            CategoriaItem = 1,
                            DescricaoItem = "Transforma a magia Espirito Vingativo em uma horda de voláteis flukes bebês.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/7/7d/Wayward_Compass.png/revision/latest/scale-to-width-down/76?cb=20231011215858&path-prefix=pt",
                            IdItem = 16,
                            NomeItem = "Ninho de Flukes"
                        },
                        new
                        {
                            Id = 17,
                            CategoriaItem = 1,
                            DescricaoItem = "Causa o portador a emitir um odor heróico.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/5/56/Defender%27s_Crest.png/revision/latest/scale-to-width-down/76?cb=20231011224240&path-prefix=pt",
                            IdItem = 17,
                            NomeItem = "Insignia do Defensor"
                        },
                        new
                        {
                            Id = 18,
                            CategoriaItem = 1,
                            DescricaoItem = "Drena a ALMA de seu portador e utiliza-a para parir crias.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/c/c6/Glowing_Womb.png/revision/latest/scale-to-width-down/76?cb=20231011224432&path-prefix=pt",
                            IdItem = 18,
                            NomeItem = "Útero Brilhante"
                        },
                        new
                        {
                            Id = 19,
                            CategoriaItem = 1,
                            DescricaoItem = "Aumenta a velocidade do foco da ALMA, permitindo que o portador se cure mais rapidamente.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/6/6a/Quick_Focus.png/revision/latest/scale-to-width-down/76?cb=20231011224556&path-prefix=pt",
                            IdItem = 19,
                            NomeItem = "Foco Rápido"
                        },
                        new
                        {
                            Id = 20,
                            CategoriaItem = 1,
                            DescricaoItem = "O portador irá focar ALMA em um ritmo mais lento, mas o efeito de cura será dobrado.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/e/ea/Deep_Focus.png/revision/latest/scale-to-width-down/76?cb=20231011224730&path-prefix=pt",
                            IdItem = 20,
                            NomeItem = "Foco Profundo"
                        },
                        new
                        {
                            Id = 21,
                            CategoriaItem = 1,
                            DescricaoItem = "Ao descansar, o portador irá ganhar uma camada de Sangue Vital que lhe protege de uma moderada quantidade de dano.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/7/7c/Lifeblood_Heart.png/revision/latest/scale-to-width-down/76?cb=20231011224903&path-prefix=pt",
                            IdItem = 21,
                            NomeItem = "Coração de Sangue Vital"
                        },
                        new
                        {
                            Id = 22,
                            CategoriaItem = 1,
                            DescricaoItem = "Ao descansar, o portador irá ganhar uma camada de Sangue Vital que lhe protege de uma grande quantidade de dano.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/8/81/Lifeblood_Core.png/revision/latest/scale-to-width-down/76?cb=20231011225103&path-prefix=pt",
                            IdItem = 22,
                            NomeItem = "Núcleo de Sangue Vital"
                        },
                        new
                        {
                            Id = 23,
                            CategoriaItem = 1,
                            DescricaoItem = "O portador terá uma carapaça mais saudável e poderá receber mais dano, porém ele será incapaz de curar se curar focando ALMA.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/6/67/Joni%27s_Blessing.png/revision/latest/scale-to-width-down/76?cb=20231011225246&path-prefix=pt",
                            IdItem = 23,
                            NomeItem = "Bênção de Joni"
                        },
                        new
                        {
                            Id = 24,
                            CategoriaItem = 1,
                            DescricaoItem = "Recebe ALMA sempre que dano for recebido.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/7/78/Grubsong.png/revision/latest/scale-to-width-down/76?cb=20231011225502&path-prefix=pt",
                            IdItem = 24,
                            NomeItem = "Canção das Larvas"
                        },
                        new
                        {
                            Id = 25,
                            CategoriaItem = 1,
                            DescricaoItem = "Infunde armas com uma energia sagrada. Quando o portador está com a vida cheia, ele lançará feixes de energia branca através de seu ferrão.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/b/bd/Grubberfly%27s_Elegy.png/revision/latest/scale-to-width-down/76?cb=20231011225628&path-prefix=pt",
                            IdItem = 25,
                            NomeItem = "Elegia da Larvamosca"
                        },
                        new
                        {
                            Id = 26,
                            CategoriaItem = 1,
                            DescricaoItem = "Cura as feridas do portador ao longo do tempo, permitindo-o recuperar vida sem focar ALMA.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/e/eb/Hiveblood.png/revision/latest/scale-to-width-down/76?cb=20231011225751&path-prefix=pt",
                            IdItem = 26,
                            NomeItem = "Sangue da Colmeia"
                        },
                        new
                        {
                            Id = 27,
                            CategoriaItem = 1,
                            DescricaoItem = "Quando Focando ALMA, emite uma nuvem de esporos que danifica lentamente os inimigos.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/7/78/Spore_Shroom.png/revision/latest/scale-to-width-down/76?cb=20231011230005&path-prefix=pt",
                            IdItem = 27,
                            NomeItem = "Cogumelo com Esporos"
                        },
                        new
                        {
                            Id = 28,
                            CategoriaItem = 1,
                            DescricaoItem = "Ao se utilizar Esquiva Sombria, o corpo do portador se afiará e danificará inimigos.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/1/13/Sharp_Shadow.png/revision/latest/scale-to-width-down/76?cb=20231011230112&path-prefix=pt",
                            IdItem = 28,
                            NomeItem = "Sombra Afiada"
                        },
                        new
                        {
                            Id = 29,
                            CategoriaItem = 1,
                            DescricaoItem = "Enquanto estiver focando ALMA, o portador irá assumir uma nova forma e pode mover-se livremente para evitar inimigos.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/b/b4/Shape_of_Unn.png/revision/latest/scale-to-width-down/76?cb=20231011230259&path-prefix=pt",
                            IdItem = 29,
                            NomeItem = "Forma de Unn"
                        },
                        new
                        {
                            Id = 30,
                            CategoriaItem = 1,
                            DescricaoItem = "Aumenta a maestria do portador sob as Artes do Ferrão, permitindo-o focar seus poderes mais rapidamente, e os liberar mais cedo.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/0/0f/Nailmaster%27s_Glory.png/revision/latest/scale-to-width-down/76?cb=20231011230425&path-prefix=pt",
                            IdItem = 30,
                            NomeItem = "Glória do Mestre do Ferrão"
                        },
                        new
                        {
                            Id = 31,
                            CategoriaItem = 1,
                            DescricaoItem = "Permite ao portador carregar o Ferrão dos Sonhos mais rapidamente e coletar mais ALMA atingindo inimigos.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/9/94/Dream_Wielder.png/revision/latest/scale-to-width-down/76?cb=20231011230608&path-prefix=pt",
                            IdItem = 31,
                            NomeItem = "Portador dos Sonhos"
                        },
                        new
                        {
                            Id = 32,
                            CategoriaItem = 1,
                            DescricaoItem = "Amuleto sagrado simbolizando a união entre seres superiores. O portador irá lentamente absorver a ALMA ilimitada contida interiormente. Abre o caminho para o Local de Nascimento.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/3/34/Kingsoul.png/revision/latest/scale-to-width-down/76?cb=20231012001528&path-prefix=pt",
                            IdItem = 32,
                            NomeItem = "Alma do Rei"
                        },
                        new
                        {
                            Id = 33,
                            CategoriaItem = 1,
                            DescricaoItem = "Um vazio escondido interiormente, agora sem restrições. Unifica o vazio sob a vontade do portador. Este amuleto é parte do portador e não pode ser desequipado.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/b/bb/Void_Heart.png/revision/latest/scale-to-width-down/76?cb=20231012001701&path-prefix=pt",
                            IdItem = 33,
                            NomeItem = "Coração Vazio"
                        },
                        new
                        {
                            Id = 34,
                            CategoriaItem = 1,
                            DescricaoItem = "Conjura um escudo que segue o portador e tenta protegê-lo",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/4/47/Dreamshield.png/revision/latest/scale-to-width-down/76?cb=20171102193106&path-prefix=pt",
                            IdItem = 34,
                            NomeItem = "Escudo dos Sonhos"
                        },
                        new
                        {
                            Id = 35,
                            CategoriaItem = 1,
                            DescricaoItem = "Invoca pequenas tecelãs para dar ao portador solitário um pouco de companheirismo e proteção.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/2/26/Weaversong.png/revision/latest/scale-to-width-down/76?cb=20171102193112&path-prefix=pt",
                            IdItem = 35,
                            NomeItem = "Canção das Tecelãs"
                        },
                        new
                        {
                            Id = 36,
                            CategoriaItem = 1,
                            DescricaoItem = "Usado por aqueles que participam do Ritual da Trupe Grimm. O portador deve buscar os Grimmários e coletar suas chamas. Chamas não coletadas aparecerão no mapa do portador.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/9/91/Grimmchild.png/revision/latest/scale-to-width-down/76?cb=20171102193127&path-prefix=pt",
                            IdItem = 36,
                            NomeItem = "Mestre da Corrida"
                        },
                        new
                        {
                            Id = 37,
                            CategoriaItem = 1,
                            DescricaoItem = "Contém uma música de proteção que pode defender o portador de danos.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/c/c4/Carefree_Melody.png/revision/latest/scale-to-width-down/76?cb=20171102193135&path-prefix=pt",
                            IdItem = 37,
                            NomeItem = "Melodia Despreocupada"
                        },
                        new
                        {
                            Id = 38,
                            CategoriaItem = 1,
                            DescricaoItem = "Aumenta a vida do portador.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/1/13/Fragile_Heart.png/revision/latest/scale-to-width-down/76?cb=20230804191026&path-prefix=pt",
                            IdItem = 38,
                            NomeItem = "Coração Frágil"
                        },
                        new
                        {
                            Id = 39,
                            CategoriaItem = 1,
                            DescricaoItem = "Faz com que o portador encontre mais Geo ao derrotar inimigos.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/b/b6/Fragile_Greed.png/revision/latest/scale-to-width-down/76?cb=20231010030754&path-prefix=pt",
                            IdItem = 39,
                            NomeItem = "Ganância Frágil"
                        },
                        new
                        {
                            Id = 40,
                            CategoriaItem = 1,
                            DescricaoItem = "Fortalece o portador, aumentando o dano causado aos inimigos com o ferrão.",
                            FotoItem = "https://static.wikia.nocookie.net/hollowknight/images/7/7b/Fragile_Strength.png/revision/latest/scale-to-width-down/76?cb=20231010224857&path-prefix=pt",
                            IdItem = 40,
                            NomeItem = "Força Frágil"
                        });
                });

            modelBuilder.Entity("HollowKnightAPI.models.Mob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Dificultade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Forca")
                        .HasColumnType("int");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localizacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonagemId")
                        .HasColumnType("int");

                    b.Property<int?>("PontosVida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonagemId");

                    b.ToTable("TB_MOBS");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = 1,
                            Dificultade = "E",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/c/c2/False_Knight_Icon.png/revision/latest/scale-to-width-down/100?cb=20181005213247",
                            Localizacao = "Encruzilhada esquecida",
                            Lore = "Falso Cavaleiro é um Verme vestindo a armadura de Hegemol, um dos Cinco Cavaleiros Reais de Hallownest. Esta criatura fraca queria encontrar meios de proteger seus irmãos que vivem em um depósito abandonado no meio da Encruzilhada Esquecida. Quando ele descobriu Hegemol dormindo em sua concha blindada, ele a pegou para si, esperando pela grande força que usar a armadura parecia prometer. Mesmo que a loucura não o tenha levado a fazer isso, o Falso Cavaleiro acabou caindo nas mãos da Infecção.",
                            Nome = "O Falso Cavaleiro",
                            PontosVida = 105
                        },
                        new
                        {
                            Id = 2,
                            Categoria = 1,
                            Dificultade = "E",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/e/e2/Gruz_Mother_Icon.png/revision/latest/scale-to-width-down/100?cb=20181005205907",
                            Localizacao = "Encruzilhada Esquecida",
                            Lore = "Uma Mãe Mosca pode ser encontrada bloqueando o caminho direto para uma vila abandonada no fundo da Encruzilhada Esquecida. Ela está dormindo, exausta de carregar seus filhos, e acorda quando é atingida. Após a derrota, seu estômago explode para revelar um enxame de Moscas.",
                            Nome = "Mãe Mosca",
                            PontosVida = 90
                        },
                        new
                        {
                            Id = 3,
                            Categoria = 1,
                            Dificultade = "E",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/0/08/Vengefly_King_Icon.png/revision/latest/scale-to-width-down/100?cb=20180827013512",
                            Localizacao = "Caminho Verde",
                            Lore = "Reis Vengemoscas são os patriarcas territoriais das Vengemoscas e são nativos do Caminho Verde.[",
                            Nome = "Rei Vengemosca",
                            PontosVida = 55
                        },
                        new
                        {
                            Id = 4,
                            Categoria = 1,
                            Dificultade = "D",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/e/e9/Hornet_Protector_Icon.png/revision/latest/scale-to-width-down/100?cb=20181005204201",
                            Localizacao = "Caminho Verde",
                            Lore = "Hornet é a misteriosa princesa-protetora das ruínas de Hallownest, uma personagem importante de Hollow Knight e protagonista de Hollow Knight: Silksong.",
                            Nome = "Hornet Protetora",
                            PontosVida = 225
                        },
                        new
                        {
                            Id = 5,
                            Categoria = 1,
                            Dificultade = "E",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/3/3d/Massive_Moss_Charger_Icon.png/revision/latest/scale-to-width-down/100?cb=20180827013444",
                            Localizacao = "Caminho Verde",
                            Lore = "O Batedor Musgoso Imenso é um mini-chefe opcional no Hollow Knight e encontramos no caminho verde. ",
                            Nome = "Batedor Musgoso Imenso",
                            PontosVida = 480
                        },
                        new
                        {
                            Id = 6,
                            Categoria = 1,
                            Dificultade = "B",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/b/b2/Mantis_Lords_Icon.png/revision/latest/scale-to-width-down/100?cb=20170511203618",
                            Localizacao = "Ermos Fúngicos",
                            Lore = "As Lordes Louva-a-Deus são três irmãs que comandam a Tribo-Louva-a-Deus nas profundezas dos Ermos Fúngicos. Eles conseguiram resistir à Infecção durante a queda de Hallownest, exceto o irmão e seus seguidores, que escolheram aceitar a Infecção voluntariamente.",
                            Nome = "Lordes Louva-a-Deus",
                            PontosVida = 530
                        },
                        new
                        {
                            Id = 7,
                            Categoria = 1,
                            Dificultade = "C",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/0/0c/Soul_Warrior_Icon.png/revision/latest/scale-to-width-down/100?cb=20181005211941",
                            Localizacao = "Santuário das Almas",
                            Lore = "???",
                            Nome = "Guerreiro das Almas",
                            PontosVida = 175
                        },
                        new
                        {
                            Id = 8,
                            Categoria = 1,
                            Dificultade = "B",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/e/e9/Soul_Master_Icon.png/revision/latest/scale-to-width-down/100?cb=20181005205259",
                            Localizacao = "Santuário das Almas",
                            Lore = "O Mestre das Almas é o líder do Santuário das Almas de Hallownest, que procurou maneiras de expandir as mentes dos insetos e atingir o foco puro. Quando a Infecção começou, ele chegou à conclusão de que ALMA, a energia que anima insetos e bestas, era a solução para curar as suas mentes dessa praga. Ele se recusou a ouvir o Rei Pálido se opondo ao seu trabalho, e não pôde perceber que a sua própria mente Infectada estava o influenciando.",
                            Nome = "Mestre das Almas",
                            PontosVida = 385
                        },
                        new
                        {
                            Id = 9,
                            Categoria = 1,
                            Dificultade = "B",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/b/bd/Dung_Defender_Icon.png/revision/latest/scale-to-width-down/100?cb=20170511203423",
                            Localizacao = "Hidrovia Real",
                            Lore = "O Defensor do Esterco costumava ser conhecido como Ogrim, o mais leal dos Cinco Grandes Cavaleiros de Hallownest. Como tal, ele participou de muitas batalhas e aventuras. Ele também era igualmente famoso por seu mau cheiro, embora isso não o impedisse de desfrutar da companhia da Dama Branca e seus companheiros cavaleiros. Ele gostava particularmente da cavaleira Isma.",
                            Nome = "Defensor do Esterco",
                            PontosVida = 700
                        },
                        new
                        {
                            Id = 10,
                            Categoria = 1,
                            Dificultade = "E",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/6/61/Flukemarm_Icon.png/revision/latest/scale-to-width-down/100?cb=20181005212623",
                            Localizacao = "Hidrovia Real",
                            Lore = "Flukemarm é a mãe de todos os Flukes que infestam a Hidrovia Real. Seu corpo é usado como um ninho para Flukefeys jovens. Assim como seus filhos, ela foi Infectada e hostilizada, embora sua condição de reprodutora a impeça de sair de sua caverna.",
                            Nome = "Flukemarm",
                            PontosVida = 350
                        },
                        new
                        {
                            Id = 11,
                            Categoria = 1,
                            Dificultade = "B",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/e/e6/Broken_Vessel_Icon.png/revision/latest/scale-to-width-down/100?cb=20170511203343",
                            Localizacao = "Bacia Antiga",
                            Lore = "O Receptáculo Quebrado é um dos vários Receptáculos que escapou do O Abismo. Porém, diferente do Cavaleiro, ele teve uma morte trágica enquanto ainda estava em Hallownest. Sua carcaça foi abandonada em uma profunda caverna ventosa na Bacia Antiga a frente da região que fica as Asas do Monarca onde a Infecção tomou conta.",
                            Nome = "Receptáculo Quebrado",
                            PontosVida = 525
                        },
                        new
                        {
                            Id = 12,
                            Categoria = 1,
                            Dificultade = "C",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/a/af/Crystal_Guardian_Icon.png/revision/latest/scale-to-width-down/100?cb=20181005210132",
                            Localizacao = "Pico de Cristal",
                            Lore = "O Guardião Cristalizado faz parte dos mineradores do Pico de Cristal que morreram pela Infecção e foram reanimados por ela. Ele parece maior do que as outras carcaças, tem cristais crescendo em suas costas e envolvendo seus braços e sua cabeça. Ele também tem mais domínio sobre a luz do cristal do que as Carcaças Cristalizadas.",
                            Nome = "Guardião de Cristal",
                            PontosVida = 280
                        },
                        new
                        {
                            Id = 13,
                            Categoria = 1,
                            Dificultade = "C",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/6/6f/Brooding_Mawlek_Icon.png/revision/latest/scale-to-width-down/100?cb=20170511203411",
                            Localizacao = "Encruzilhada Esquecida",
                            Lore = "Um solitário Mawlek Incubador pode ser encontrado fora do caminho na Encruzilhada Esquecida, longe do seu irmão vivo na Bacia Antiga. Ele fica em meio a restos fossilizados de seus parentes, pedindo que reproduzam. Essa besta selvagem foi conduzida tanto pela solidão quanto pela Infecção que começou cobrindo seu corpo com bulbos.",
                            Nome = "Mawlek Incubador",
                            PontosVida = 300
                        },
                        new
                        {
                            Id = 14,
                            Categoria = 1,
                            Dificultade = "A",
                            Forca = 2,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/1/15/Traitor_Lord_Icon.png/revision/latest/scale-to-width-down/100?cb=20181005205522",
                            Localizacao = "Jardins da Rainha",
                            Lore = "O Lorde Traidor foi um dos líderes da Tribo Louva-a-Deus, junto de suas irmãs, além de ser particularmente ressentido a respeito de Hallownest.[2] De forma semelhante, ele desaprovava o relacionamento de sua filha com a Pranteadora Cinzenta, por ela ser um ser de fora.",
                            Nome = "Lorde Traidor",
                            PontosVida = 800
                        },
                        new
                        {
                            Id = 15,
                            Categoria = 1,
                            Dificultade = "A",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/b/b3/Watcher_Knight_Icon.png/revision/latest/scale-to-width-down/100?cb=20181005211823",
                            Localizacao = "Cidade das Lágrimas",
                            Lore = "???",
                            Nome = "Cavaleiro Sentinela",
                            PontosVida = 100
                        },
                        new
                        {
                            Id = 16,
                            Categoria = 1,
                            Dificultade = "C",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/d/d9/Uumuu_Icon.png/revision/latest/scale-to-width-down/100?cb=20170511210950",
                            Localizacao = "Arquivos da Professora",
                            Lore = "Uumuu é um ser inteligente, porém Infectado, semelhante aos Uomas e Oomas que infestam o Cânion da Névoa. É responsável por defender a câmara de Monomon no coração dos Arquivos da Professora.",
                            Nome = "Uumuu",
                            PontosVida = 300
                        },
                        new
                        {
                            Id = 17,
                            Categoria = 1,
                            Dificultade = "C",
                            Forca = 1,
                            Foto = "https://hollowknight.fandom.com/wiki/Brothers_Oro_%26_Mato",
                            Localizacao = "Torre do Amor",
                            Lore = "O Colecionador é uma criatura feita de Vazio. Ele vive escondido na Torre do Amor trancado junto com uma grande coleção de insetos de toda Hallownest que são preservados, vivos ou mortos, em jarras de vidro.",
                            Nome = "O Colecionador",
                            PontosVida = 750
                        },
                        new
                        {
                            Id = 18,
                            Categoria = 1,
                            Dificultade = "A",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/e/e9/Hornet_Protector_Icon.png/revision/latest/scale-to-width-down/100?cb=20181005204201",
                            Localizacao = "Borda do Reino",
                            Lore = "Hornet Sentinela é a segunda forma de Hornet como uma chefe em Hollow Knight. Ela desafia o Cavaleiro na entrada da Casca Descartada na Borda do Reino para testar sua determinação e força para salvar Hallownest. Dessa vez, ela emprega toda a sua força e ferramentas.",
                            Nome = "Hornet Sentinela",
                            PontosVida = 700
                        },
                        new
                        {
                            Id = 19,
                            Categoria = 1,
                            Dificultade = "A",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/8/8a/Nosk_Icon.png/revision/latest/scale-to-width-down/100?cb=20170511203627",
                            Localizacao = "Ninho Profundo",
                            Lore = "Nosk é uma besta Infectada misteriosa e metamórfica caçando no Ninho Profundo. Ele pode imitar a forma de rostos que encontra nas memórias de insetos, geralmente entes queridos ou falecidos, e pode contorcer seu corpo para assumir uma moldura menor. Ele pendura suas presas, incluindo Escavadores, um Devoto Espreitador, e vários Receptáculos, no teto do seu covil no fundo do Ninho Profundo.",
                            Nome = "Nosk",
                            PontosVida = 680
                        },
                        new
                        {
                            Id = 20,
                            Categoria = 1,
                            Dificultade = "A",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/5/5f/Hive_Knight_Icon.png/revision/latest/scale-to-width-down/100?cb=20181005210625",
                            Localizacao = "Colmeia",
                            Lore = "Cavaleiro da Colmeia é o cavaleiro mais valente e habilidoso da Colmeia; ele não voa e é obrigado a proteger a Rainha da Colmeia Vespa pela mente coletiva das Abelhas. Embora a Infecção tenha se espalhado para a Colmeia depois que a rainha morreu, o Cavaleiro da Colmeia ainda a protege, esperando que ela um dia acorde e reviva a Colmeia.",
                            Nome = "Cavaleiro da Colmeia",
                            PontosVida = 800
                        },
                        new
                        {
                            Id = 21,
                            Categoria = 1,
                            Dificultade = "C",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/6/66/Oblobble_Icon.png/revision/latest/scale-to-width-down/100?cb=20181005204959",
                            Localizacao = "Coliseu dos Tolos",
                            Lore = "Os Obbles são parentes maiores do Obble e são capazes de se mover mais rápido e disparar mais projéteis por ataque. O Cavaleiro pode encontrar dois deles no Coliseu dos Tolos durante o Julgamento do Conquistador. Esses Oblobbles são criados e treinados dentro do Coliseu para participar da luta contra os gladiadores. Matar um enfurece o outro e faz com que ele se mova e ataque mais rápido.",
                            Nome = "Oblobles",
                            PontosVida = 560
                        },
                        new
                        {
                            Id = 22,
                            Categoria = 1,
                            Dificultade = "B",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/1/19/God_Tamer_Icon.png/revision/latest/scale-to-width-down/100?cb=20181005211000",
                            Localizacao = "Coliseu dos Tolos",
                            Lore = "A Domadora de Deuses é uma guerreira veterana do Coliseu dos Tolos, tomando o lugar de chefe do último e mais brutal julgamento. Ela compensa por sua pequena estatura com a força de sua Besta domesticada, ao lado da qual ela luta. Ambos apresentam sinais da Infecção.",
                            Nome = "Domador de Deuses",
                            PontosVida = 105
                        },
                        new
                        {
                            Id = 23,
                            Categoria = 1,
                            Dificultade = "S",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/2/24/The_Hollow_Knight_Icon.png/revision/latest/scale-to-width-down/100?cb=20181005212233",
                            Localizacao = "Ovo Negro",
                            Lore = "O Cavaleiro Vazio é um Receptáculo escolhido pelo Rei Pálido para selar a Radiância e salvar Hallownest da Infecção. Como seus irmãos, ele era um filho do Rei e da Rainha de Hallownest, nascido no Abismo e preenchido com o poder do Vazio. Sendo assim, nenhum deles tem gênero. A condição desse nascimento consequentemente os deixaria sem mente, vontade ou voz, para prevenir que A Radiância não os influenciasse. No entanto, sua pureza foi mal avaliada, manchada por uma ideia instintiva, o laço com o Rei Pálido, aquele que os criou.",
                            Nome = "Cavaleiro Vazio",
                            PontosVida = 1250
                        },
                        new
                        {
                            Id = 24,
                            Categoria = 1,
                            Dificultade = "S",
                            Forca = 2,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/b/b8/Radiance_Icon.png/revision/latest/scale-to-width-down/100?cb=20181005204741",
                            Localizacao = "Cavaleiro Vazio",
                            Lore = "A Radiância é um ser superior de luz semelhante à Essência e, como tal, oposta ao Vazio , seu antigo inimigo. A Tribo Mariposa nasce de sua luz e em troca a reverencia.",
                            Nome = "Radiância",
                            PontosVida = 1700
                        },
                        new
                        {
                            Id = 25,
                            Categoria = 1,
                            Dificultade = "B",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/6/64/Elder_Hu_Icon.png/revision/latest/scale-to-width-down/97?cb=20181211041949",
                            Localizacao = "Cidade das Lágrimas",
                            Lore = "Ancião Hu era um sábio viajante que procurou purificar as fronteiras de Hallownest da Infecção. Ele alcançou a Vila Louva-a-Deus, mas sua própria mente Infectada o fez ver os Lordes Louva-a-Deus e a Tribo como afligidos pela praga. Os Louva-a-Deus o mataram depois que ele os atacou. Um memorial foi erguido em seu nome acima dos portões da Cidade das Lágrimas, com sua túnica e colar de contas repousando sobre o memorial.",
                            Nome = "Ancião Hu",
                            PontosVida = 250
                        },
                        new
                        {
                            Id = 26,
                            Categoria = 1,
                            Dificultade = "B",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/6/6f/Galien_Icon.png/revision/latest/scale-to-width-down/100?cb=20181005214202",
                            Localizacao = "Ninho Profundo",
                            Lore = "Galien era um guerreiro corajoso e invicto que dizia ser o mais forte em Hallownest e desejava provar seu valor ao Rei Pálido como um Cavaleiro. Ele viajou para Ninho Profundo para testar sua força, mas acabou encontrando a morte. Sua casca está em uma caverna cheia de cogumelos brilhantes incomumente grandes abaixo da Linha de Bonde Inacabada em Ninho Profundo.",
                            Nome = "Galien",
                            PontosVida = 650
                        },
                        new
                        {
                            Id = 27,
                            Categoria = 1,
                            Dificultade = "B",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/2/27/Gorb_Icon.png/revision/latest/scale-to-width-down/100?cb=20181005214152",
                            Localizacao = "Pico Uivante",
                            Lore = "Gorb, a Grande Mente, era uma criatura mística com um cérebro distendido que afirmava ser onisciente. Eles incitaram outros a reverenciar suas mentes e ascender com eles a um plano diferente de existência. Seus restos mortais foram enterrados em uma colina no topo dos Penhascos Uivantes, com uma lápide esculpida em sua imagem. O fantasma de Gorb aparece em seu túmulo após adquirir o ferrão dos sonhos.",
                            Nome = "Gorb",
                            PontosVida = 320
                        },
                        new
                        {
                            Id = 28,
                            Categoria = 1,
                            Dificultade = "A",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/4/44/Markoth_Icon.png/revision/latest/scale-to-width-down/100?cb=20170511213232",
                            Localizacao = "Borda do Reino",
                            Lore = "Markoth é uma Mariposa. Aparentemente amigo de Thistlewind, eles são as únicas Mariposas a empunhar um ferrão de forma agressiva, sendo encontrado na borda do reino, dando 250 essências como recompensa.",
                            Nome = "Markoth",
                            PontosVida = 105
                        },
                        new
                        {
                            Id = 29,
                            Categoria = 1,
                            Dificultade = "C",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/1/10/Marmu_Icon.png/revision/latest/scale-to-width-down/100?cb=20170511213232",
                            Localizacao = "Jardins da Rainha",
                            Lore = "Marmu foi uma protetora inocente, porém forte, dos Jardins da Rainha. A Rainha prometeu ensiná-la a como voar quando retornasse ao seu retiro verdejante. Marmu faleceu antes desse dia, e um totem em sua memória foi erguido em seu túmulo nos confins do jardim.",
                            Nome = "Marmu",
                            PontosVida = 200
                        },
                        new
                        {
                            Id = 30,
                            Categoria = 1,
                            Dificultade = "C",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/7/79/No_Eyes_Icon.png/revision/latest/scale-to-width-down/100?cb=20170511213232",
                            Localizacao = "Caminho Verde",
                            Lore = "Sem olhos (No Eyes) foi um guerreiro do Hallownest que caiu na infecção. Ela não conseguia dormir sabendo que os sonhos infectariam sua mente com a luz. Para proteger a si mesma e a outros insetos, ela arrancou seus olhos e os dela antes de sucumbir. Ela foi sepultada no Santuário de Pedra, um lugar completamente escuro, e uma estátua esculpida foi colocada sobre seu túmulo.",
                            Nome = "Sem Olhos",
                            PontosVida = 320
                        },
                        new
                        {
                            Id = 31,
                            Categoria = 1,
                            Dificultade = "B",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/0/00/Xero_Icon.png/revision/latest/scale-to-width-down/100?cb=20170511213232",
                            Localizacao = "Terra do Descanso",
                            Lore = "Xero era um guerreiro de Hallownest que acreditava que a força sempre lhe permitiria um futuro brilhante. Quando sua mente foi infectada, ele esperava lutar contra a praga com violência.",
                            Nome = "Xero",
                            PontosVida = 320
                        },
                        new
                        {
                            Id = 32,
                            Categoria = 1,
                            Dificultade = "A",
                            Forca = 2,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/c/c2/False_Knight_Icon.png/revision/latest/scale-to-width-down/100?cb=20181005213247",
                            Localizacao = "Encruzilhada Esquecida",
                            Lore = "Campeão Fracassado é um chefe escondido em Hollow Knight. Ele é a variante dos Sonhos do Falso Cavaleiro, sendo mais forte e ágil do que o seu equivalente físico.",
                            Nome = "Campeão Fracassado",
                            PontosVida = 1260
                        },
                        new
                        {
                            Id = 33,
                            Categoria = 1,
                            Dificultade = "A",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/e/e6/Broken_Vessel_Icon.png/revision/latest/scale-to-width-down/100?cb=20170511203343",
                            Localizacao = "Bacia Antiga",
                            Lore = "Parente Perdido é um chefe oculto em Hollow Knight. É a variante dos Sonhos do Receptáculo Quebrado, mais rápida e mais resistente do que sua contraparte física.",
                            Nome = "Parente Perdido",
                            PontosVida = 1200
                        },
                        new
                        {
                            Id = 34,
                            Categoria = 1,
                            Dificultade = "SS",
                            Forca = 2,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/8/81/Grey_Prince_Zote_Circle.png/revision/latest/scale-to-width-down/100?cb=20170810232902",
                            Localizacao = "Dirmouth",
                            Lore = "???",
                            Nome = "Príncipe Cinza Zote",
                            PontosVida = 1
                        },
                        new
                        {
                            Id = 35,
                            Categoria = 1,
                            Dificultade = "S",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/8/80/White_defender_circle_.png/revision/latest/scale-to-width-down/99?cb=20170810232928",
                            Localizacao = "Hidrovia Real",
                            Lore = "Defensor Branco é um chefe oculto em Hollow Knight. É a variante dos Sonhos do Defensor de Esterco",
                            Nome = "Defensor Branco",
                            PontosVida = 105
                        },
                        new
                        {
                            Id = 36,
                            Categoria = 1,
                            Dificultade = "S",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/2/23/Troupe_Master_Grimm_Icon.png/revision/latest/scale-to-width-down/100?cb=20181005211608",
                            Localizacao = "Dirmouth (DLC)",
                            Lore = "Grimm é o lider da Trupe Grimm, da DLC The Grimm Troupe, um misterioso circo itinerante.",
                            Nome = "Grimm",
                            PontosVida = 1000
                        },
                        new
                        {
                            Id = 37,
                            Categoria = 1,
                            Dificultade = "SS",
                            Forca = 2,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/c/c3/Nightmare_King_Icon.png/revision/latest/scale-to-width-down/100?cb=20181005215902",
                            Localizacao = "Dirmouth (DLC)",
                            Lore = "Rei do Pesadelo Grimm é o chefe final opcional de A Trupe Grimm em Hollow Knight. Ele é a forma dos Sonhos do Mestre da Trupe Grimm.",
                            Nome = "Rei do Pesadelo Grimm",
                            PontosVida = 1500
                        },
                        new
                        {
                            Id = 38,
                            Categoria = 1,
                            Dificultade = "SS",
                            Forca = 2,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/b/b1/Pure_Vessel_Icon.png/revision/latest/scale-to-width-down/100?cb=20180827013611",
                            Localizacao = "Panteão de Hollownest",
                            Lore = "O Receptáculo Puro é um chefe opcional de Hollow Knight introduzido em Deus Mestre. Ele é a forma primordial do Cavaleiro Vazio, a forma não afetada pela Infecção.",
                            Nome = "Receptáculo Puro",
                            PontosVida = 1600
                        },
                        new
                        {
                            Id = 39,
                            Categoria = 1,
                            Dificultade = "A",
                            Forca = 2,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/a/af/Crystal_Guardian_Icon.png/revision/latest/scale-to-width-down/100?cb=20181005210132",
                            Localizacao = "Pico de Cristal",
                            Lore = "Guardião Enfurecido é um chefe em Hollow Knight. É a variante do Guardião Cristalizado",
                            Nome = "Guardião Enfurecido",
                            PontosVida = 280
                        },
                        new
                        {
                            Id = 40,
                            Categoria = 1,
                            Dificultade = "S",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/c/c1/Winged_Nosk_Icon.png/revision/latest/scale-to-width-down/100?cb=20180827013634",
                            Localizacao = "Panteão de Hollownest",
                            Lore = "Nosk Alado é um chefe em Hollow Knight introduzido em Deus Mestre. É a forma voadora de Nosk, assumindo a forma da Hornet no início, em vez do Cavaleiro. Ele pode ser encontrado no Panteão de Hallownest.",
                            Nome = "Nosk Alado",
                            PontosVida = 750
                        },
                        new
                        {
                            Id = 41,
                            Categoria = 1,
                            Dificultade = "A",
                            Forca = 1,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/e/e9/Soul_Master_Icon.png/revision/latest/scale-to-width-down/100?cb=20181005205259",
                            Localizacao = "Santuário das Almas",
                            Lore = "O Tirano das Almas é um chefe oculto em Hollow Knight. É a variante dos sonhos do Mestre das Almas, mais rápido e mais resistente do que sua contraparte física.",
                            Nome = "Tirano das Almas",
                            PontosVida = 1250
                        },
                        new
                        {
                            Id = 42,
                            Categoria = 1,
                            Dificultade = "E",
                            Forca = 0,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/1/12/Zote_Circle-2.png/revision/latest/scale-to-width-down/100?cb=20180831184143",
                            Localizacao = "Coliseu dos Tolos",
                            Lore = "Zote o Poderoso é um NPC em Hollow Knight. É um viajante de fora de Hallownest que veio para cumprir uma promessa.",
                            Nome = "Zote o Poderoso",
                            PontosVida = 200
                        },
                        new
                        {
                            Id = 43,
                            Categoria = 1,
                            Dificultade = "SS",
                            Forca = 2,
                            Foto = "https://static.wikia.nocookie.net/hollowknight/images/6/68/Absolute_Radiance_Icon.png/revision/latest/scale-to-width-down/100?cb=20180827013551",
                            Localizacao = "Panteão de Hollownest",
                            Lore = "A Radiância é um chefe secreto em Hollow Knight. Godmaster Icon Radiância Absoluta é sua forma perfeita que é encontrada no topo do panteão de Hallownest.",
                            Nome = "Radiância Absoluta",
                            PontosVida = 1700
                        });
                });

            modelBuilder.Entity("RpgApi.Models.Personagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdPersonagem")
                        .HasColumnType("int");

                    b.Property<string>("NomePersonagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TB_PERSONAGENS");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdPersonagem = 1,
                            NomePersonagem = "O Cavaleiro"
                        });
                });

            modelBuilder.Entity("HollowKnightAPI.models.Item", b =>
                {
                    b.HasOne("RpgApi.Models.Personagem", null)
                        .WithMany("PersonagemItens")
                        .HasForeignKey("PersonagemId");
                });

            modelBuilder.Entity("HollowKnightAPI.models.Mob", b =>
                {
                    b.HasOne("RpgApi.Models.Personagem", null)
                        .WithMany("Mobs")
                        .HasForeignKey("PersonagemId");
                });

            modelBuilder.Entity("RpgApi.Models.Personagem", b =>
                {
                    b.Navigation("Mobs");

                    b.Navigation("PersonagemItens");
                });
#pragma warning restore 612, 618
        }
    }
}
